from typing import List, Tuple
from app.models import Finding, ReviewResult, Severity

def dedupe_findings(findings: List[Finding]) -> List[Finding]:
    """Deduplicate findings having identical path, line, and message content."""
    seen = set()
    out = []
    for f in findings:
        key = (f.path, f.line, f.message.strip().lower())
        if key in seen:
            continue
        seen.add(key)
        out.append(f)
    return out

def build_summary(
    result: ReviewResult,
    skipped_files: List[Tuple[str, str]],
) -> str:
    """Builds a rich markdown review summary body."""
    bugs = result.count(Severity.BUG)
    warnings = result.count(Severity.WARNING)
    suggestions = result.count(Severity.SUGGESTION)
    total = bugs + warnings + suggestions

    lines = ["## 🤖 AI Code Reviewer Summary", ""]
    lines.append(
        f"**Files reviewed**: {result.files_reviewed} | **Findings**: {total} "
        f"({bugs} 🔴 bugs · {warnings} 🟡 warnings · {suggestions} 🔵 suggestions)"
    )

    if total == 0:
        lines += ["", "✅ LGTM! No issues were identified in the reviewed changes."]

    sections = [
        (Severity.BUG, "### 🔴 Bugs"),
        (Severity.WARNING, "### 🟡 Warnings"),
        (Severity.SUGGESTION, "### 🔵 Suggestions"),
    ]

    for severity, header in sections:
        items = [f for f in result.findings if f.severity == severity]
        if not items:
            continue
        lines += ["", header]
        lines += [f"- `{f.path}:{f.line}` — {f.message}" for f in items]

    if skipped_files:
        lines += ["", "### ⚪ Skipped Files"]
        lines += [f"- `{path}` — {reason}" for path, reason in skipped_files]

    lines += ["", "---", f"_Generated by AI Code Reviewer using `{result.model}`_"]
    return "\n".join(lines)